### ISSUE TITLE
Error loading pretrained model: xxx is a zip archive (did you mean to use torch.jit.load()?)

### ISSUE THREAD

**Issue by xiaoda99** [facebookresearch/anli#15]
Hi,
When trying to load anli pretrained model with the following code:
  hg_model_hub_name = "ynie/roberta-large-snli_mnli_fever_anli_R1_R2_R3-nli"
  model = AutoModelForSequenceClassification.from_pretrained(hg_model_hub_name)
I got error::
RuntimeError: /home/xd/.cache/torch/transformers/05b820b482aacc2f4ab9fc864c2acc45307024b2d4ebb2458686967bf2697fe3.d5336e8b7525ed52f95265359a6bdc77551bbf8e69e271a19d8c1817385fd345 is a zip archive (did you mean to use torch.jit.load()?)
After search, I found it may be caused by loading pytorch 1.6 models from an older pytorch version.
My env:
pytorch: 1.3
huggingface/transformers: 3.02
Did you train and save the model using pytorch 1.6? What is the version requirement for pytorch and huggingface/transformers?

- Da Xiao

**Comment by easonnie** [comment]
Hi, @xiaoda99 thanks for the reporting. The code should work with torch==1.6 or later and transformers==3.0.2 or later.
