### ISSUE TITLE
Questions regarding full score calculation

### ISSUE THREAD

**Issue by bminixhofer** [facebookresearch/anli#16]
Hi!

I'm a bit confused regarding how the full ANLI (A1+A2+A3) score is calculated. My understanding is that it is a sample-weighted average of the A1, A2 and A3 sets. Is that correct?

So like this:
```python
def anli(a1, a2, a3):
    return (a1 * 1000 + a2 * 1000 + a3 * 1200) / 3200
```

When I try this on the [InfoBERT](https://arxiv.org/pdf/2010.02329v2.pdf) paper the calculation matches for some scores but not for others (from Table 2):

```python
 # FreeLB
anli(73.3, 50.5, 46.8) # 56.24, matches the paper

# SMART
anli(72.4, 49.8, 50.3) # 57.05, matches the paper

# ALUM
anli(72.3, 52.1, 48.4) # 57.02, matches the paper

# InfoBERT
anli(75.0, 50.5, 47.7) # 57.1 while paper shows 58.3 ???
```

__Question 1: Is this a mistake in the paper or is the way I calculate the total score wrong?__

But what confused me again was that in the Table 5 in the [ALUM paper](https://arxiv.org/pdf/2004.08994.pdf):

![image](https://user-images.githubusercontent.com/13353204/104224313-1f53e300-5445-11eb-86a3-68cf700b7668.png)

The authors say 

> Note that Nie et al. (2019) did not represent results for individual rounds, assignified by “-”

Comparing this with Table 3 in the [original ANLI paper](https://arxiv.org/pdf/1910.14599.pdf) this doesn't seem to match:

![image](https://user-images.githubusercontent.com/13353204/104224551-6e9a1380-5445-11eb-9198-d5f186b2d7b6.png)

Although it's not very explicitly said here I interpret this table as follows:

A1 column -> test score for A1
A2 column -> test score for A2
A3 column -> test score for A3
ANLI column -> test score for ANLI
ANLI-E column -> test score for ANLI-E, a more difficult subset of the ANLI test set

while the authors of the ALUM paper interpret it as follows:

A1 column -> dev score for A1
A2 column -> dev score for A2
A3 column -> dev score for A3
ANLI column -> dev score for ANLI
ANLI-E column -> test score for ANLI

The same thing occurs in the [SMART paper](https://arxiv.org/pdf/1911.03437.pdf) (Table 6):

![image](https://user-images.githubusercontent.com/13353204/104224969-039d0c80-5446-11eb-8737-c37b46f345fc.png)

If my interpretation is right this is a significant flaw in the paper as they compare dev scores with test scores.

__Question 2: Which interpretation of Table 3 in the ANLI paper is correct?__

Thanks for your help.

**Comment by boxin-wbx** [comment]
Hi,

I am the author of InfoBERT. Thanks a lot for the good observation. We did make a mistake when putting the experimental logs into the paper. The correct A1, A2, A3 scores on the ANLI test set are respectively 75.5, 51.4, and 49.8. We will update our paper immediately.

We have made our code and checkpoint publicly available at https://github.com/AI-secure/InfoBERT. Feel free to play with our code and reproduce our results using the provided script and checkpoint.

Thanks!

**Comment by bminixhofer** [comment]
Hi, thanks for fixing the mistake! Good that it was in this direction :slightly_smiling_face:  Really impressive scores!

**Comment by easonnie** [comment]
Hi @bminixhofer,

Thanks for bringing this to our attention. We hope to clarify any confusion regarding the issues. 

> “I'm a bit confused regarding how the full ANLI (A1+A2+A3) score is calculated. My understanding is that it is a sample-weighted average of the A1, A2, and A3 sets. Is that correct?”

Yes, you’re correct. The full ANLI score is the sample-weighted average of the A1, A2, and A3 sets.

> “Which interpretation of Table 3 in the ANLI paper is correct?”

Your interpretation is correct. All the numbers in Table 3 of the ANLI paper show the test numbers except the MNLI.

It appears that a line of prior works (SMART, ALUM, InfoBERT) misinterprets our results in the ANLI paper. We will notify them to update the numbers and will update the Github to be even more explicit about this.

Let me know if there is any other confusion. Again, we really appreciate your attention on the matter and hope it can clear any confusion.


Also, thank you @boxin-wbx for the clarification.

**Comment by namisan** [comment]
@bminixhofer and @easonnie , thanks for pointing it out. We'll update the paper. By the way, @easonnie is it possible to report dev results in ANLI paper. The mix dev/test is reported in tab 3 which is misleading.

**Comment by easonnie** [comment]
Hi @namisan, thank you for your reply. Sorry about the confusion. We will try to clarify it thereafter. I'm not sure whether I can find some old dev results. Let me try to get back to you later.

**Comment by easonnie** [comment]
Hi everyone @bminixhofer @boxin-wbx @namisan, thank you guys again for the valuable feedback.

We just updated the leaderboard with some new numbers to try to clean out any confusion. Now that the leaderboard contains numbers that can align with the numbers in the ANLI paper. We also provide the expected numbers (both dev/test) you can get using the script in this codebase in a new table below the leaderboard.

Thanks again, everyone. I will close the issue this weekend if there is no other problem on this thread.

**Comment by bminixhofer** [comment]
Thanks for the clarifications and thanks to the authors for quickly fixing the issues! From my side everything is clear now so this issue can be closed.
