### ISSUE TITLE
RuntimeError: No rendezvous handler for env://

### ISSUE THREAD

**Issue by wjddd** [facebookresearch/anli#20]
Hi, with this command:

```
python src/nli/training.py \
    --model_class_name "roberta-large" \
    -n 1 \
    -g 1 \
    -nr 0 \
    --max_length 156 \
    --gradient_accumulation_steps 1 \
    --per_gpu_train_batch_size 16 \
    --per_gpu_eval_batch_size 16 \
    --save_prediction \
    --train_data snli_train:none,mnli_train:none \
    --train_weights 1,1 \
    --eval_data snli_dev:none \
    --eval_frequency 2000 \
    --experiment_name "roberta-large|snli|nli"
```

I got this error:

> Traceback (most recent call last):
>   File "src/nli/training.py", line 854, in <module>
>     main()
>   File "src/nli/training.py", line 377, in main
>     mp.spawn(train, nprocs=args.gpus_per_node, args=(args,))  # spawn how many process in this node
>   File "C:\Users\1111\AppData\Roaming\Python\Python37\site-packages\torch\multiprocessing\spawn.py", line 199, in spawn
>     return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
>   File "C:\Users\1111\AppData\Roaming\Python\Python37\site-packages\torch\multiprocessing\spawn.py", line 157, in start_processes
>     while not context.join():
>   File "C:\Users\1111\AppData\Roaming\Python\Python37\site-packages\torch\multiprocessing\spawn.py", line 118, in join
>     raise Exception(msg)
> Exception:
> 
> -- Process 0 terminated with the following error:
> Traceback (most recent call last):
>   File "C:\Users\1111\AppData\Roaming\Python\Python37\site-packages\torch\multiprocessing\spawn.py", line 19, in _wrap
>     fn(i, *args)
>   File "F:\3233\anli\src\nli\training.py", line 425, in train
>     rank=args.global_rank
>   File "C:\Users\1111\AppData\Roaming\Python\Python37\site-packages\torch\distributed\distributed_c10d.py", line 434, in init_process_group
>     init_method, rank, world_size, timeout=timeout
>   File "C:\Users\1111\AppData\Roaming\Python\Python37\site-packages\torch\distributed\rendezvous.py", line 82, in rendezvous
>     raise RuntimeError("No rendezvous handler for {}://".format(result.scheme))
> RuntimeError: No rendezvous handler for env://

Could you please help me with this?

**Comment by easonnie** [comment]
Hi @wjddd, thank you for pointing it out. It seems to be a windows-specific error. Did you try the single GPU mode?

https://github.com/PyTorchLightning/pytorch-lightning/issues/5358

**Comment by wjddd** [comment]
> Hi @wjddd, thank you for pointing it out. It seems to be a windows-specific error. Did you try the single GPU mode?
> 
> [PyTorchLightning/pytorch-lightning#5358](https://github.com/PyTorchLightning/pytorch-lightning/issues/5358)

OK, problem solved, thanks a lot!
