### ISSUE TITLE
About accuracy number reported in the paper

### ISSUE THREAD

**Issue by WANGXinyiLinda** [facebookresearch/anli#21]
Hi, I am just wondering how do you calculate the number under the ANLI column in Table 3? It doesn't seem like any weighted/unweighted average from A1, A2, A3?

**Comment by easonnie** [comment]
Hi @WANGXinyiLinda, thanks for reaching out.

A1, A2, A3 contain 1000, 1000, and 1200 examples respectively. The ANLI column shows the accuracy on all the 3200 (1000 + 1000 + 1200) examples. So, the formula should be `acc_ANLI = (1.0 * acc_A1 + 1.0 * acc_A2 + 1.2 * acc_A3) / 3.2`.

**Comment by easonnie** [comment]
@WANGXinyiLinda, I will close this issue soon. Please feel free to reopen it if there is any confusion raises.
