### ISSUE TITLE
Model Size

### ISSUE THREAD

**Issue by AhmedKhaled945** [facebookresearch/anli#24]
Wanted to ask if there is a way to reduce the model size, i was trying to use the code locally instead of google Collab and my ram didn't manage to let the model load,

As i see, the ynie/roberta-large-snli_mnli_fever_anli_R1_R2_R3-nli is roughly 1.5 GB, is this the quantized version?

Thanks in advance.

**Comment by easonnie** [comment]
Hi @AhmedKhaled945, this is normal RoBERTa model and not the quantized version.
