### ISSUE TITLE
Is path name correctly defined?

### ISSUE THREAD

**Issue by hansd410** [facebookresearch/anli#26]
I think path is defined incorrectly.

for [training data](https://github.com/facebookresearch/anli/blob/4a3756984889250b032b1019b072231395f0bf89/src/nli/training.py#L471)
        path = name[ind + 1:]

and [dev data](https://github.com/facebookresearch/anli/blob/4a3756984889250b032b1019b072231395f0bf89/src/nli/training.py#L492)
        path = name[ind + 1:]

I think name should be changed to named_path. Is it correct?

**Comment by contracode** [comment]
I think it is a bug. I submitted PR https://github.com/facebookresearch/anli/pull/29 to fix this.

**Comment by easonnie** [comment]
Thank you @contracode! Issue closed.
