### ISSUE TITLE
Hyperparameters

### ISSUE THREAD

**Issue by robinsongh381** [facebookresearch/anli#28]
Hello !
Thank you for sharing a great piece of work.

I was wondering what are the exact hyperparameters for producing Table 3 for each of BERT, XLNET and RoBETa.

Regards

**Comment by easonnie** [comment]
Hi @robinsongh381, thanks for reach out. Please refer to https://github.com/facebookresearch/anli/blob/main/script/example_scripts/train_roberta.sh regarding the hyperparameters used in those models. To the best of my recollection, you can use the same hyperparameters to produce the results.
