### ISSUE TITLE
[Request] Pretrained Weights 

### ISSUE THREAD

**Issue by yukioichida** [facebookresearch/anli#7]
Hi,

- Since you used the Transformer library from hugging face to write your code, can you upload the finetuned models used in the paper in the hugging face [models](https://huggingface.co/models)?

**Comment by easonnie** [comment]
Hi @yukioichida,

Thank you for your great suggestion. We will work on releasing the models. The tentative timeline for that is the next two weeks.

**Comment by yukioichida** [comment]
Hi @easonnie 

Thanks for the answer, I am requesting the pretrained models just to replicate your experiments as well as using the NLI Model to do transfer learning for my research. Besides that, I do not have a robust GPU and even with Colab I think that the experiments with more than one dataset will demand a lot of time. 

But don't worry about the deadline, take your time.

**Comment by easonnie** [comment]
The pre-trained-model can be used with the following script. The model is `roberta-large` trained on `snli + mnli  + fever_nli + anli-R1,R2,R3`.

```
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

if __name__ == '__main__':
    max_length = 256

    premise = "Two women are embracing while holding to go packages."
    hypothesis = "The men are fighting outside a deli."

    tokenizer = AutoTokenizer.from_pretrained("ynie/roberta-large-snli_mnli_fever_anli_R1_R2_R3-nli")
    model = AutoModelForSequenceClassification.from_pretrained("ynie/roberta-large-snli_mnli_fever_anli_R1_R2_R3-nli")

    tokenized_input_seq_pair = tokenizer.encode_plus(premise, hypothesis,
                                                     max_length=max_length,
                                                     return_token_type_ids=True, truncation=True)

    input_ids = torch.Tensor(tokenized_input_seq_pair['input_ids']).long().unsqueeze(0)
    token_type_ids = torch.Tensor(tokenized_input_seq_pair['token_type_ids']).long().unsqueeze(0)
    attention_mask = torch.Tensor(tokenized_input_seq_pair['attention_mask']).long().unsqueeze(0)

    outputs = model(input_ids,
                    attention_mask=attention_mask,
                    token_type_ids=token_type_ids,
                    labels=None)

    predicted_probability = torch.softmax(outputs[0], dim=1)[0].tolist()    # batch_size only one

    print("Premise:", premise)
    print("Hypothesis:", hypothesis)
    print("Entailment:", predicted_probability[0])
    print("Neutral:", predicted_probability[1])
    print("Contradiction:", predicted_probability[2])
```

Let me know if you have any questions.

**Comment by yukioichida** [comment]
Hi @easonnie 

Thank you so much for made available such models!

Unfortunately, I am very busy during this month and probably I will not doing test using this pretrained model, but I recommend to put this script in the README file since it is very clear and intuitively.

I will close this issue/request.
